name: 'inclusivator'
description: 'Checks for non inclusive comments'
inputs:
  token:
    required: false
    description: Token used to fetch the repository
    default: ${{ github.token }}
  tba:  # id of input 
    description: 'Default reply text'
    required: true
    default: 'Dude! cmon.. u can do better.. check the Code of Conduct pls!'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'alert-triangle' # icon referenced from https://feathericons.com/
  color: 'yellow'
