name: Inclusivator-check

on:
  pull_request:
    types: [assigned, opened, edited, reopened, synchronize, ready_for_review]
  issue_comment:
    types: [created, edited]

jobs:
  inclusivator-warning:

    name: Inclusivator-check
    runs-on: ubuntu-latest

    steps:
      - name: Get Repo Code
        id: get_repo_code
        uses: actions/checkout@v2

      - name: Inclusivator-check
        id: inclusivator_check
        uses: ./
        with:
          tba: 'Dude! cmon.. u can do better.. check the Code of Conduct pls!' # Reply text
